{% set name = "Dispenso" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/facebookincubator/dispenso/archive/v{{ version }}.tar.gz
    sha256: d1c84ba77d6d3a0da24010a930c81acb4c149532afd8ab352c9cae54c51b6f72

build:
  number: 5
  run_exports:
    - {{ pin_subpackage('dispenso', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]

test:
  commands:
    - test -f $PREFIX/lib/cmake/Dispenso-{{ version }}/DispensoConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\Dispenso-{{ version }}\\DispensoConfig.cmake exit 1  # [win]

about:
  home: https://github.com/facebookincubator/dispenso
  summary: 'The project provides high-performance concurrency, enabling highly parallel computation.'
  description: |
    Dispenso is a library for working with sets of tasks in parallel. It provides mechanisms for
    thread pools, task sets, parallel for loops, futures, pipelines, and more. Dispenso is a
    well-tested C++14 library designed to have minimal dependencies (some dependencies are required
    for the tests and benchmarks), and designed to be clean with compiler sanitizers (ASAN, TSAN).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebookincubator/dispenso

extra:
  recipe-maintainers:
    - jeongseok-meta
