{% set name = "Dispenso" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/facebookincubator/dispenso/archive/v{{ version }}.tar.gz
    sha256: e75b2a1bd428b2e9558ea99c03d266d2bf8881ba41689016e8c98052e1a0c17d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('dispenso', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]

test:
  commands:
    - bash run_test.sh  # [unix]
    - call run_test.bat  # [win]
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - run_test.sh
    - run_test.bat
    - tests/

about:
  home: https://github.com/facebookincubator/dispenso
  summary: 'The project provides high-performance concurrency, enabling highly parallel computation.'
  description: |
    Dispenso is a library for working with sets of tasks in parallel. It provides mechanisms for
    thread pools, task sets, parallel for loops, futures, pipelines, and more. Dispenso is a
    well-tested C++14 library designed to have minimal dependencies (some dependencies are required
    for the tests and benchmarks), and designed to be clean with compiler sanitizers (ASAN, TSAN).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebookincubator/dispenso

extra:
  recipe-maintainers:
    - jeongseok-meta
